.proxyrc.js
src/navigators/PopupWindow.ts
test/unit/PopupWindow.test.ts

This PR uses postmessage logic to send data back to the main window
todo:

feature PopupWindow postmessage

---

docs/migration.md
docs/oidc-client-ts.api.md
package-lock.json
package.json
samples/Parcel/src/code-flow-identityserver/sample-settings.js
src/OidcClient.ts
src/OidcClientSettings.ts
src/ResponseValidator.ts
src/SigninRequest.ts
src/SigninResponse.ts
src/SignoutRequest.ts
src/User.ts
src/UserInfoService.ts
src/UserManager.ts
src/UserManagerSettings.ts
src/utils/JwtUtils.ts
src/utils/index.ts
test/unit/OidcClient.test.ts
test/unit/OidcClientSettings.test.ts
test/unit/ResponseValidator.test.ts
test/unit/SigninRequest.test.ts
test/unit/SigninResponse.test.ts
test/unit/SignoutRequest.test.ts
test/unit/UserInfoService.test.ts
test/unit/UserManager.test.ts
test/unit/UserManagerSettings.test.ts
test/unit/utils/JwtUtils.test.ts

Most parts of this commit bring back previous functionality. For reviewing i need to know that we have now all needed.
What is new:
- JwtUtils +JwtUtils.test.ts
As we do no longer use jsrsasign i have added the helper class as we need to decode at multiple places: JwtUtils, which is using a decent jwt decode library, no crypto/signature validation is needed and done anymore.

revert removing too much from commit "remove implicit flow" and adapt

---

.gitignore
api-extractor.json
dist/esm/package.json
package.json
scripts/build.js
src/utils/CryptoUtils.ts

i have now removed the x.esm.js rename, its not needed

add sourcemaps

---

src/JsonService.ts

Returns proper json message in exception

Updates postForm to return JSON error message

---

docs/oidc-client-ts.api.md
src/UserManager.test.ts
src/UserManager.ts

- the signoutCallback always throws otherwise an error
- found issue by writing tests

fix signout callback

---

samples/Parcel/src/code-flow-identityserver/sample-callback.js
samples/Parcel/src/code-flow-identityserver/sample-popup-signin.js
samples/Parcel/src/code-flow-identityserver/sample-popup-signout.js
samples/Parcel/src/code-flow-identityserver/sample-silent.js
samples/Parcel/src/code-flow-identityserver/sample.js
samples/Parcel/src/oidc-client/sample-callback.js
samples/Parcel/src/oidc-client/sample.js
samples/Parcel/src/user-manager/sample-callback.js
samples/Parcel/src/user-manager/sample-popup-signin.js
samples/Parcel/src/user-manager/sample-popup-signout.js
samples/Parcel/src/user-manager/sample-silent.js
samples/Parcel/src/user-manager/sample.js
src/ErrorResponse.ts
src/OidcClientSettings.ts
src/UserManagerSettings.ts
src/utils/CryptoUtils.ts
src/utils/Timer.ts

- add minimal SSR support
- in g_timer i completely drop window, seems to still call "global" function and was like that in oidc-client-js as well
- improve the logging of sample/Parcel to easier find problems
- fix sample/Parcel custom state
fixes part of #256

minimal ssr support

---

docs/oidc-client-ts.api.md
src/index.ts
src/utils/Log.ts

fix(#278): expose the internal logger

---

.github/pull_request_template.md
.husky/pre-commit

chore: update API report on pre-commit

---

docs/oidc-client-ts.api.md
src/Claims.ts
src/OidcClient.test.ts
src/ResponseValidator.test.ts
src/ResponseValidator.ts
src/SigninResponse.ts
src/User.ts
src/UserInfoService.ts
src/UserManager.test.ts
src/index.ts
src/utils/JwtUtils.ts

@pamapa, sorry for the last PR. I went too fast on that one.
Here is a cleaner one and test should pass 😉

feat(claims): improve claims types

---

docs/index.md
package-lock.json
samples/Parcel/package.json
samples/Parcel/src/code-flow-identityserver/sample.html
samples/Parcel/src/oidc-client/sample.html
samples/Parcel/src/user-manager/sample.html
src/TokenClient.ts

small stuff

---

docs/migration.md
src/JsonService.test.ts
src/JsonService.ts
src/TokenClient.test.ts
src/TokenClient.ts
src/UserInfoService.test.ts
src/UserInfoService.ts

As suggested in MR #338. To be merged after #338...

refactor: align arguments in json service

---

docs/index.md

document cognito limitation, no support for iframe prompt=none

---

src/RefreshState.ts

refactor: RefreshState does not need to implement State

---

src/ResponseValidator.test.ts
src/ResponseValidator.ts

allow to get and process claims when scope does not contain openid

---

docs/oidc-client-ts.api.md
src/OidcClient.ts
src/ResponseValidator.ts
src/SessionMonitor.ts
src/SigninState.ts
src/State.ts
src/User.ts
src/UserInfoService.ts
src/UserManager.ts
src/utils/Logger.test.ts
src/utils/Logger.ts

- introduce `Logger.createStatic`
- logging related cosmetics

Improve static logging

---

docs/oidc-client-ts.api.md
src/OidcClient.test.ts
src/OidcClient.ts
src/SigninRequest.test.ts
src/SigninRequest.ts
src/UserManager.test.ts
src/UserManager.ts
src/navigators/IWindow.ts

feature(nonce): allow nonce fowarding through signin

---

docs/oidc-client-ts.api.md
src/UserManager.ts

allow passing post_logout_redirect_uri to signoutRedirect

---

src/ResponseValidator.ts

only validate sub during refresh token path when the optional id_token is present

---

src/utils/UrlUtils.test.ts
src/utils/UrlUtils.ts

origin based URL fix #534

---

docs/oidc-client-ts.api.md
src/UserManager.test.ts
src/UserManager.ts

allow override of prompt on signin

---

docs/oidc-client-ts.api.md
src/OidcClient.test.ts
src/RefreshState.ts
src/ResponseValidator.ts
src/SigninResponse.ts
src/UserManager.test.ts

preserve session_state during refresh token

---

docs/oidc-client-ts.api.md
src/UserManagerSettings.ts
src/navigators/RedirectNavigator.test.ts
src/navigators/RedirectNavigator.ts

Adds ability to redirect window top when used within iFrame

---

package.json

Support TS 4.7 moduleResolution Node16/NodeNext

---

src/OidcClient.test.ts
src/RefreshState.ts
src/ResponseValidator.ts
src/UserManager.test.ts

fix id_token is lost on silent refresh token renewal

---

samples/Parcel/package-lock.json
samples/Parcel/package.json

Closes/fixes #issue https://github.com/authts/oidc-client-ts/issues/741
see link issue for full detail
I took the opportunity to bump "all" deps since there's only 4 of them

ensure parcel / lmdb / nodegyp etc properly use pre-build native

---

docs/oidc-client-ts.api.md
src/OidcClientSettings.ts
src/TokenClient.ts

add `revokeTokenContentTypes` settings to pass into `JsonService`

---

docs/oidc-client-ts.api.md
src/UserManager.test.ts
src/UserManager.ts
src/UserManagerSettings.ts

Add silent signout functionality

---

.github/workflows/ci.yml
.github/workflows/release.yml

ci: actions bump

---

docs/oidc-client-ts.api.md
src/OidcClient.ts
src/OidcClientSettings.ts
src/SigninRequest.test.ts
src/SigninRequest.ts

allow multiple resource parameters

---

docs/oidc-client-ts.api.md
src/Claims.ts
src/OidcClientSettings.test.ts
src/OidcClientSettings.ts
src/ResponseValidator.test.ts
src/ResponseValidator.ts

fix(#780): filterProtocolClaims deletes properties required by the IdTokenClaims type

---

docs/oidc-client-ts.api.md
src/OidcClient.test.ts
src/OidcClient.ts
src/OidcClientSettings.ts

Closes/fixes #695. See discussion in this issue.

Fix #695: Add filter list to scopes used with refresh tokens

---

docs/oidc-client-ts.api.md
src/UserManager.ts

Adding login_hint passthrough into ExtraSigninRequestArgs.

Add login hint

---

docs/oidc-client-ts.api.md
src/UserManager.ts

Same idea as https://github.com/authts/oidc-client-ts/pull/691 and https://github.com/authts/oidc-client-ts/pull/859. I am using the scope value for incremental authorization and it appears to be working.

Add scope to ExtraSigninRequestArgs

---

docs/index.md

improve projects using oidc-client section

---

docs/oidc-client-ts.api.md
src/OidcMetadata.ts

describe the openid metadata as per openid specifications

---

docs/oidc-client-ts.api.md
src/MetadataService.ts
src/OidcClient.ts
src/SigninRequest.ts
src/SigninResponse.ts
src/SignoutRequest.ts
src/SignoutResponse.ts
src/TokenClient.ts

This merge request adds some links to specs and simplifies code duplication in interface definition.

Improve doc and simplify interface

---

docs/oidc-client-ts.api.md
src/UserManager.ts

fix: included max_age in sign in args

---

src/UserManagerSettings.ts

closes https://github.com/authts/oidc-client-ts/issues/996

fix: impove comment

---

package-lock.json
package.json
src/MetadataService.test.ts
src/OidcClient.test.ts
src/OidcClient.ts
src/OidcClientSettings.ts
src/SigninRequest.test.ts
src/SignoutRequest.test.ts
src/TokenClient.test.ts
src/UserManager.test.ts
src/UserManager.ts
src/UserManagerSettings.ts
src/navigators/IFrameNavigator.ts
src/navigators/PopupNavigator.ts
src/navigators/PopupWindow.ts
src/utils/Logger.test.ts
tsconfig.json

update typescript to 5.0.4

---

docs/oidc-client-ts.api.md
src/OidcClient.ts

Closes #919
I didn't add ResponseValidator & TokenClient to the constructor params since they're currently not exported from the package

Add OidcClient constructor overload

---

docs/migration.md

Update migration.md with changed behavior of User.expired

---

src/navigators/PopupWindow.test.ts
src/navigators/PopupWindow.ts

Fix Popup window not close after some time

---

package.json

bump crypto-js dependency to v4.2.0

---

docs/migration.md
docs/oidc-client-ts.api.md
src/OidcClientSettings.test.ts
src/OidcClientSettings.ts

drop deprecated settings

---

docs/migration.md
docs/oidc-client-ts.api.md
src/OidcClientSettings.ts

Response mode optional

---

docs/protocols/authorization-code-grant-with-pkce.md
docs/protocols/silent-refresh-token-in-iframe-flow.md

doc: place notes better

---

docs/index.md

After submitting https://github.com/authts/oidc-client-ts/pull/1270 I guess this is the way to go

Add section about hash-mode routing

---

.gitignore
src/UserManager.test.ts

Improve unit tests

---

src/JsonService.test.ts
src/MetadataService.test.ts
src/OidcClient.test.ts
src/TokenClient.test.ts
src/UserInfoService.test.ts
src/UserManager.test.ts
src/UserManagerEvents.test.ts
src/navigators/IFrameWindow.test.ts
src/navigators/PopupWindow.test.ts
src/utils/Event.test.ts
src/utils/Timer.test.ts

improve unit-tests

---

docs/oidc-client-ts.api.md
src/OidcMetadata.ts

doc: improve descriptions

---

samples/Parcel/.proxyrc.js

typo in sample app config

---

docs/index.md

fix link to issue

---

docs/oidc-client-ts.api.md
src/UserManager.ts

make signoutCallback return signout response if request_type is so:r

---

.github/workflows/ci.yml
.github/workflows/release.yml

chore: use node 18.x, prepare publish to previous tag and avoid deploying pages

---

.github/workflows/ci.yml

make sure CI runs on branch release/v2

---

docs/oidc-client-ts.api.md
src/UserManager.ts

this is a backport to the 2.4.x series of https://github.com/authts/oidc-client-ts/pull/1672,  but a branch doesn't exist for me to open a PR against.

fix: return signout response from signoutCallback

---

.husky/pre-commit

avoid husky deprecated warning

---

package-lock.json
package.json
src/JsonService.ts

bump typescript from 5.4.5 to 5.7.2

---

docs/oidc-client-ts.api.md
src/UserManagerSettings.ts

Closes/fixes #1850
Replaces #1851 and #1936

change userStore from WebStorageStateStore to StateStore

---

jest-environment-jsdom.cjs
src/navigators/AbstractChildWindow.ts
src/navigators/IFrameWindow.test.ts
src/navigators/PopupWindow.test.ts
src/navigators/PopupWindow.ts

Allows Cross-Origin-Opener-Policy="same-origin", which is what Amazon Cognito returns.
Closes/fixes #1896
- [ X] I have included links for closing relevant issue numbers

fix: use BroadcastChannel if no window.opener

---

.github/workflows/ci.yml
.github/workflows/release.yml

update pipeline to node 20

---

src/JsonService.test.ts
src/UserManager.test.ts
src/navigators/IFrameWindow.test.ts

avoid test functions dropped in jest v3
