.eslintrc.yml, docs/oidc-client-ts.api.md, src/CheckSessionIFrame.ts, src/SessionMonitor.ts, src/SilentRenewService.ts, src/UserInfoService.ts, src/UserManager.ts, src/UserManagerSettings.ts, src/navigators/IFrameNavigator.ts, src/navigators/IFrameWindow.ts, src/navigators/INavigator.ts, src/navigators/IWindow.ts, src/navigators/PopupNavigator.ts, src/navigators/PopupWindow.ts, src/navigators/RedirectNavigator.ts, src/utils/Event.ts, src/utils/Timer.ts, test/unit/PopupWindow.test.ts, test/unit/UserManager.test.ts
Resolves #95.
This restores the ability to customize the window behavior of the Popup, IFrame, and Redirect navigators. The existing `NavigatorParams` interface was taking on too many parameters that weren't related to the actual `.navigate()` step during sigin/signout. I've split the following settings out of that interface and made them customizable via params passed to the `.signin*()`/`.signout*()` methods:
* `popupWindowFeatures`
* `popupWindowTarget`
* `silentRequestTimeoutInSeconds`
* `redirectMethod`
This PR has some clean up commits, I recommend reviewing 678ef18 in isolation for a clear view of the refactoring for the above settings.
These changes contain one potentially breaking change where the popup's redirect method is no longer customizable and uses the `'replace'` method …
=> Support passing window params to UserManager functions

docs/oidc-client-ts.api.md, src/OidcClient.ts, src/UserManager.ts, src/UserManagerEvents.ts, src/index.ts, src/navigators/PopupWindow.ts, src/navigators/RedirectNavigator.ts
Additional to the lint fixes, i tweaked the API and we need to export more.
esbuild is more conservative than tsdx regarding exporting, which is good. I am for now only exporting what is needed by the context library. We might need to export more, we can do this later when requested.
In order to pass-through the APT arguments for signinRequest, ... i have introduced separate types, this makes it much more easy.
All seen when trying to use this library here: https://github.com/pamapa/react-oidc-context/pull/78
=> fix lint warnings and exports

docs/oidc-client-ts.api.md, samples/Parcel/src/user-manager/sample.js, src/ErrorResponse.ts, src/OidcClient.ts, src/ResponseValidator.ts, src/SigninRequest.ts, src/SigninResponse.ts, src/SignoutResponse.ts, src/State.ts, src/User.ts, src/UserManager.ts, test/unit/OidcClient.test.ts, test/unit/ResponseValidator.test.ts, test/unit/SigninResponse.test.ts, test/unit/SignoutResponse.test.ts
- additionally i spitted the confusing "state" property in xResponse.ts class used as state id query parameter and the optional custom state passed by the user.
For the public API (request + User): 
- state is the optional custom state
in xResponse classes:
- state is the query response state=id -> id
- state_data is the optional custom state
=> round tripping "state" is missing

docs/oidc-client-ts.api.md, src/OidcClient.ts, src/OidcClientSettings.ts, src/UserManager.ts
- response_mode is kept
- by made easier, by setting by default query
- fragment response_mode is still possible
=> default response mode is explicit query

.proxyrc.js, docs/oidc-client-ts.api.md, src/UserManager.ts, src/navigators/AbstractChildWindow.ts, src/navigators/IFrameNavigator.ts, src/navigators/IFrameWindow.ts, src/navigators/IWindow.ts, src/navigators/PopupNavigator.ts, src/navigators/PopupWindow.ts, src/navigators/RedirectNavigator.ts, src/utils/Event.ts, test/unit/AccessTokenEvents.test.ts, test/unit/PopupWindow.test.ts
This cleans up navigator code. There might be some subtle differences from how things worked before, but I feel confident that this new implementation is much more robust. It has a couple of important improvements:
* callbacks attempt to compare to the `MessageEvent.source` property rather that the state ID. Not all browsers support this feature, so it still falls back to comparing to the state ID of the current navigation. This allows the navigator to recover even when the state param is entirely missing from the iframe/popup callback page.
* message payloads are encoded with a `source` key to prevent other libraries from interfering with navigator callbacks. The old code was deserializing with `JSON.parse` which could cause some console spam triggered by React dev tools while a popup …
=> Refactor navigators

docs/oidc-client-ts.api.md, src/OidcClient.ts, src/SigninRequest.ts, src/SigninResponse.ts, src/SigninState.ts, src/SignoutRequest.ts, src/SignoutResponse.ts, src/UserManager.ts, src/navigators/AbstractChildWindow.ts, src/navigators/IFrameNavigator.ts, src/navigators/IFrameWindow.ts, src/navigators/IWindow.ts, src/navigators/PopupNavigator.ts, src/navigators/PopupWindow.ts, src/utils/UrlUtils.ts, test/unit/OidcClient.test.ts, test/unit/PopupWindow.test.ts, test/unit/SigninResponse.test.ts, test/unit/SignoutResponse.test.ts, test/unit/utils/UrlUtils.test.ts
Closes #157
This refactors navigator code a bit further:
* URL parsing is now dictated solely by the settings of the window opener/iframe parent. The previous implementation extracted the `state` param from the URL on the child window and passed it separately from the full URL in `.postMessage()`.  Essentially this means that before, when using `response_mode=fragment`, the child window `settings` must match its parent since the parent window parses the URL according to its own `response_mode` setting after the navigator completes.
* `_signinCallback()` was inlined since the refactoring above made it into a trivial one-line function. Additionally, `signinPopupCallback` was lacking parity with `signoutPopupCallback`  w.r.t the `keepOpen` param.
=> Replace UrlUtils with WhatWG URL APIs

docs/oidc-client-ts.api.md, samples/Parcel/oidc.js, src/UserManagerSettings.ts, src/index.ts, src/navigators/PopupWindow.ts, src/utils/PopupUtils.ts, src/utils/index.ts, test/unit/UserManagerSettings.test.ts, test/unit/utils/PopupUtils.test.ts
This updates the popup window navigator to automatically open and place the window centered in front the window opener. This is accomplished by refactoring the `popupWindowFeatures` setting to be an object instead of a string and introducing a new `PopupUtils` library which can compute a centered placement based on window dimensions.
Screenshot:
=> Automatically center popups in front of the opener window

test/unit/JsonService.test.ts, test/unit/MetadataService.test.ts, test/unit/SigninResponse.test.ts
closes #214
i am using `"test": "tsc -p test/unit/tsconfig.json && jest --coverage",` to detect missing spots, we have quite some...
=> improve unit-tests for JsonService

docs/oidc-client-ts.api.md, src/JsonService.ts, src/MetadataService.ts, src/OidcClientSettings.ts, src/ResponseValidator.ts, src/TokenClient.ts, src/utils/CryptoUtils.ts, test/unit/JsonService.test.ts, test/unit/MetadataService.test.ts, test/unit/UserInfoService.test.ts
This properly resolves the issue addressed in #213 by throwing an `ErrorResponse` instance when the response is parseable as JSON and contains a `.error` value.
The unit test code checked into #215 will need some minor updates if this merges first.
=> Refactor json service

.eslintrc.yml, src/JsonService.test.ts, src/OidcClient.ts, src/SignoutRequest.test.ts, src/UserManager.test.ts, src/navigators/PopupWindow.test.ts
Adds some error handling tests for PopupWindow's and some smoke tests UserManager's redirect flows.
I'll probably be working on smoke tests for the rest of UserManager's public API next.
=> Update tests for PopupWindow and UserManager

docs/oidc-client-ts.api.md, src/User.ts
Firstly, thank-you for taking on maintenance of oidc-client (and migrating to TypeScript)
As per #125, this PR adds extra properties to UserProfile so that standard claims can be accessed by applications.
Since the code already existed to merge these claims into UserProfile (`ResponseValidator._mergeClaims()`), all this PR does is add the extra properties so that they can be accessed with TypeScript applications.
=> feat(User): add types for standard claims to UserProfile

package-lock.json, package.json, src/JsonService.test.ts, src/UserManager.test.ts, src/navigators/PopupWindow.test.ts
Recently tests have been generating many warnings over `ts-jest/utils` deprecating the `mocked` helper function. It's been moved to the `jest-mock` package.
```console
`mocked` util function is now deprecated and has been moved to Jest
repository, see https://github.com/facebook/jest/pull/12089. In `ts-jest`
v28.0.0, `mocked` function will be completely removed. Users are encouraged to
use to Jest v27.4.0 or above to have `mocked` function available from
`jest-mock`. One can disable this warning by setting environment variable
process.env.DISABLE_MOCKED_WARNING=true
```
This PR replaces instances of `import { mocked } from 'ts-jest/utils'` with `import { mocked } from 'jest-mock';`.
=> test: replace mocked ts-jest util function with jest-mock's

src/CheckSessionIFrame.ts, src/SessionMonitor.ts, src/utils/CryptoUtils.ts, src/utils/Timer.test.ts, src/utils/Timer.ts
This removes more unnecessary usage of `window`. The most important change here is that `window.crypto.getRandomValues()` is replaced by `CryptoJS.lib.WordArray.random()`. Under the hood, CryptoJS uses `window.crypto` but falls back to `window.msCrypto` (IE11) and `require('crypto')` (Node.js).
=> Additional `window` updates

docs/oidc-client-ts.api.md, src/AccessTokenEvents.ts, src/UserManagerEvents.ts
This updates the `addAccessTokenExpired`, `addUserLoaded`, etc. methods to forward the destructor function returned by the underlying `Events` class. This is a nice pattern to support since React users can integrate it into a useEffect hook:
```javascript
useEffect(() => {
return userManager.events.addAccessTokenExpiring(() => setSessionExpiring(true));
}, [userManager.events])
=> feat: return destructor functions from event listener methods

docs/migration.md, docs/oidc-client-ts.api.md, src/ErrorResponse.ts, src/JsonService.ts, src/MetadataService.ts, src/TokenClient.test.ts, src/TokenClient.ts, src/UserManager.test.ts, src/UserManager.ts, src/UserManagerSettings.test.ts, src/UserManagerSettings.ts
Resolves #262.
There's two questions that I couldn't really answer for myself while refactoring this:
1. Why does revoking tokens mutate the User? I see that since 1.x, `access_token`, `refresh_token`, `token_type`, etc. were updated to be set to empty strings after revocation rather than `null`. I don't see any benefit to doing this client-side since it would lead to unnecessarily opaque errors. If I make an API request after revoking a token, I'd rather be alerted by the API that my token is revoked and no longer valid rather than it rejecting it because I'm suddenly sending an empty string for an access token. I can see an argument for removing `refresh_token`, but everything else seems like it should stay put until the user signs out.
2. Why is revocation success optional on sign out? …
=> Refactor revoke token

src/navigators/PopupWindow.test.ts, src/navigators/PopupWindow.ts
Fixes #274. The old timer would only clean up after itself in the event that navigation was aborted (when `this._abort.raise()` is called). This issue is compounded by the fact that the `dispose()` was removing `_abort`'s ability to run clean up logic since it removed the only relevant event listener.
The fix is just to have `dispose()` clear the interval directly.
=> fix(PopupWindow): clear the interval checking popup closed on dispose

src/UserManager.ts
Small bug I noticed where `querySessionStatus` would wrongly throw if the error object contained a message that was set from the `error_description` value rather than `error`.
=> fix(UserManager): fix anonymous session monitoring

docs/oidc-client-ts.api.md, samples/Parcel/oidc.js, src/OidcClient.test.ts, src/OidcClient.ts, src/RefreshState.ts, src/ResponseValidator.test.ts, src/ResponseValidator.ts, src/SigninResponse.ts, src/TokenClient.ts, src/User.ts, src/UserManager.test.ts, src/UserManager.ts
Resolves #276.
When planning this out, I would've like to simply reuse the logic declared in `ResponseValidator`, but its private methods (and unfortunately its tests) were coupled to the use of the `SigninState` object.
In this PR I've refactored `ResponseValidator` tests to only use the public methods. I excluded `_mergeClaims` and `_filterProtocolClaims` from this since those methods are essentially utility functions that probably should be public exports in their own file(s). This allowed me to more easily refactor  `_validateTokens` and `_processClaims` to work without signin state. This will be necessary for validating refresh token responses as they do not require the same kind of state.
=> Update user profile after refresh token requests

src/UserManager.test.ts, src/navigators/PopupWindow.test.ts, src/navigators/RedirectNavigator.test.ts, src/navigators/RedirectNavigator.ts, test/setup.ts
While testing the new `activeNavigator` prop in react-oidc-context, I noticed that `signinRedirect` returns synchronously and was causing the component to immediately rerender since the redirect navigator would close immediately after invocation. To fix this, I've made it so that `navigate()` returns a promise that only resolves as the page is exiting. The timing of `beforeunload` is late enough that the tasks in the async queue waiting for the promise to resolve are never run.
=> fix(RedirectNavigator): wait until the window is unloading to resolve

samples/Parcel/src/code-flow-identityserver/sample-callback.js, samples/Parcel/src/code-flow-identityserver/sample-popup-signin.js, samples/Parcel/src/code-flow-identityserver/sample-popup-signout.js, samples/Parcel/src/code-flow-identityserver/sample-settings.js, samples/Parcel/src/code-flow-identityserver/sample-silent.js, samples/Parcel/src/code-flow-identityserver/sample.js, samples/Parcel/src/oidc-client/sample-callback.js, samples/Parcel/src/oidc-client/sample-settings.js, samples/Parcel/src/oidc-client/sample.js, samples/Parcel/src/user-manager/sample-popup-signin.js, samples/Parcel/src/user-manager/sample-popup-signout.js, samples/Parcel/src/user-manager/sample-settings.js, samples/Parcel/src/user-manager/sample-silent.js, samples/Parcel/src/user-manager/sample.js, src/navigators/IFrameWindow.ts, src/navigators/PopupWindow.ts
Closes/fixes #326
This only avoids the duplicate events raised when a popup is closed by the user or when a the iframe window times out. There are still debug logs that show when the window is closed programmatically; avoiding these would result in more complicated code that I'm not sure is worth the trouble.
=> Fix redundant window logs

src/navigators/RedirectNavigator.ts, test/setup.ts
I didn't test the fix in #329 thoroughly enough, in Edge (and presumably Chrome) I was still seeing my React app rerender and trigger another redirect, canceling the unload, and causing an infinite loop. Ideally the promise should just never resolve by the time the page is unloading, but I was having a hard time writing tests using functions that never resolve.
The use of `'unload'` here is discouraged but this case in particular seems fine to me. We don't care about browser consistency since we don't even necessarily need the promise to ever resolve, and we are truly waiting for the page to unload rather than the page visibility changing.
=> fix(RedirectNavigator): wait for 'unload' instead of 'beforeunload'

src/navigators/IFrameWindow.ts
Closes/fixes #138
I'm not sure if this fixes the whole problem but I'm also not sure what else will. This navigates the iframe to `about:blank` and waits for the page to load before removing it from DOM. In my testing, this allows for sources to unload from the "Sources" devtools panel but I'm not sure how to analyze the heap snapshots.
=> Attempt to fix iframe leak

docs/oidc-client-ts.api.md, src/JsonService.test.ts, src/OidcClient.test.ts, src/OidcClient.ts, src/UserManager.test.ts, src/UserManager.ts
When working on #338 i saw this, but i think it better to merge them independently as it will make the other MR simpler to review.
=> refactor: align arguments of useRefreshToken to other functions

docs/oidc-client-ts.api.md, src/MetadataService.ts, src/OidcClientSettings.ts, src/UserManager.ts, src/UserManagerSettings.ts, src/navigators/IFrameWindow.ts, src/navigators/PopupWindow.ts
When working on timeout for fetch i saw that it would be better to have access to the `silentRequestTimeoutInSeconds` including default applied. This was something on my to-do list for some time. And it is easier to verify the defaults, as you only have to look into the settings and not search all over the code...
=> refactor: consolidate defaults into settings

docs/oidc-client-ts.api.md, src/JsonService.ts, src/OidcClient.ts, src/TokenClient.test.ts, src/TokenClient.ts, src/UserManager.ts
By default a `fetch()` request timeouts at the time indicated by the browser. In Chrome a network request timeouts at 300 seconds, while in Firefox at 90 seconds.
The implementation is inspired by this [blog](https://dmitripavlutin.com/timeout-fetch-request/).
Closes/fixes part of #251
=> retry silent renew for fetch timeout

src/OidcClient.test.ts, src/OidcClient.ts, src/TokenClient.ts
As described in #364 Azure AD requires the scope to be sent when refreshing the access token. This adds scope to the `exchangeRefreshToken` call from `useRefreshTokens`
Closes/fixes #364
=> fix: add scope to refresh tokens

docs/oidc-client-ts.api.md, src/UserManager.ts
Allow passing id_token_hint to a signout redirect call.
Certain OIDC providers require this for their logout calls.
Closes/fixes #407
=> Type change to allow id_token_hint arg for signoutRedirect

src/ResponseValidator.ts
Currently an error occurs and token refresh fails if the token response doesn't contain the `id_token` yet the `scope` contains `openid`.
This is allowed by the OIDC spec (relevant link is in the code).
=> fix: handle case of refresh token response not containing id_token

docs/oidc-client-ts.api.md, src/UserManager.test.ts, src/UserManager.ts
This allows apps to redirect users back to the exact same place they came from. Somehow had the exact same thought at the same time as mentioned in #468 (only found the issue after trying the same thing myself!). I've tried this in my own project and do seem to end up at the right place (even when instantiating `UserManager` with a different `redirect_uri`).
Closes/fixes #468
=> Add `redirect_uri` to `ExtraSigninRequestArgs`

src/CheckSessionIFrame.ts
Closes/fixes #465
This normalizes the stored iframe origin with `new URL` which fixes the comparison to the origin in the `MessageEvent` handler later.
The existing `CheckSessionIFrame` implementation is still a bit messy. I'd like to clean up its API a bit before adding unit tests for it.
=> fix(CheckSessionIFrame): normalize iframe origin before comparing to the MessageEvent origin

src/UserManager.test.ts, src/navigators/RedirectNavigator.test.ts, src/navigators/RedirectNavigator.ts, test/setup.ts
I got a somewhat similar issue to what was reported with #329 and #330. When calling `signinRedirect`, on Chrome everything seems fine. With Firefox (at least on v99.0.1), what I see happening is that the page does redirect to the OIDC provider, but oddly an infinite barrage of API requests get made when they shouldn't - as if its trying to reload my website over and over. I can only guess this must be a bug in Firefox itself to do with making an event listener before navigating or something?
I tried listening to different events (e.g. `beforeunload`, `visibilitychange`, etc. instead of `unload`), performing the window event listening outside of the promise function (to see if ensuring that its done before navigate could help) but neither of these make a difference. The only thing that …
=> Remove the event listener for unloading when navigating

.gitignore, docs/oidc-client-ts.api.md, src/UserManager.test.ts, src/UserManager.ts, src/UserManagerSettings.ts, src/navigators/AbstractChildWindow.ts, src/navigators/IFrameNavigator.ts, src/navigators/IFrameWindow.test.ts, src/navigators/IFrameWindow.ts, src/navigators/IWindow.ts
**The problem**
Both - oidc-client-js & oidc-client-ts - support silent flow only within the same domain. However in my case - apps are hosted on different domains. It's possible to address it by specifying 2 new settings which will allow to overcome issue and make all things work even with different domains.
**What for**
I'm working on micro frontends implementation currently. 
- Architecture is based on webpack module federation and web components
- There is a shell hosted on on https://app-a.test.com
- And there is micro frontend app loaded through the shell, hosted as https://app-b.test.com
- Shell and each micro app - are separate relying parties which have their own client id, redirect urls etc.  Users can also access them directly.
The main goal is to avoid explicit login flow for …
=> feat: add ability to specify iframe script origin and iframe notify parent for silent auth

src/OidcClient.ts
This fixes the case when `clearStaleState` is never called in user code. Sooner or later `window.localStorage` is full and adding an additional state results in a `QuoteExceededError`. 
Closes/fixes #466
=> clear stale states when creating new one

docs/oidc-client-ts.api.md, src/OidcClientSettings.ts
First part for #552: As removing will cause a major version bump, we deprecate them first...
Both setting are unused. They were used for the implicit grant, which we dropped...
=> deprecated unused clockSkewInSeconds and userInfoJwtIssuer settings

docs/oidc-client-ts.api.md, src/JsonService.ts, src/OidcClient.test.ts, src/OidcClient.ts, src/OidcClientSettings.ts, src/TokenClient.ts
fixes https://github.com/authts/oidc-client-ts/issues/607
PR could be improved by allowing more `credentials` settings besides include.
the PR is very helpful in the case that the openid server sets cookies which can be updated by refresh so that silent signin works longer.
- [x ] This PR makes changes to the public API 
- [ x] I have included links for closing relevant issue numbers
=> new option refreshWithCredentials sends cookies with token refresh

src/UserManager.ts
Closes #580
- Take over from MR #612 as user has problems with formatting/git
- For now i have bound that feature to `includeIdTokenInSilentRenew` as noted in the related issue #580, if that leads to a problem for others we can still add an additional setting option.
=> add id_token_hint if present

docs/oidc-client-ts.api.md, src/UserManager.ts
Closes/fixes part of #666
I guess the next time we have to enrich that type, we should change from `Pick` to `Omit`....
=> allow to override acr_values in signinRedirect

dist/esm/package.json, docs/oidc-client-ts.api.md, src/JsonService.ts, src/MetadataService.test.ts, src/MetadataService.ts, src/OidcClient.test.ts, src/OidcClient.ts, src/OidcClientSettings.ts, src/ResponseValidator.ts, src/TokenClient.ts, src/UserInfoService.test.ts, src/UserInfoService.ts
When using a proxy or cdn like AWS cloudfront you might need to pass cookies when doing http requests from your web application to your backend service. Ex if your infrastructure requires a token cookie to pass requests through to the backend endpoints.
Right now the oidc-client-ts library doesn't support using credentials on all fetch calls. Because of this the library doesn't support the above use case.
I looked at this pull request: [https://github.com/authts/oidc-client-ts/pull/659](https://github.com/authts/oidc-client-ts/pull/659) which adds support of credentials for the refreshToken fetch request. But it is only supports refreshToken.
In my pull request I changed this to be a fetchRequestCredentials which will put credentials on all fetch calls within the library because in the …
=> Make it possible to include credentials on all requests.

src/OidcClientSettings.ts
Fix an error in the documentation for the default value of `staleStateAgeInSeconds`.  
The actual default value is 60 * 15 = 900 and not 300.
=> Fix default value documentation error

docs/oidc-client-ts.api.md, src/OidcClient.ts, src/TokenClient.ts, src/UserManager.ts
Closes/fixes #820 
Add the extraTokenParameters to the Resource Owner Password Credential Flow request to the `/token` endpoint.
- [X ] I have included links for closing relevant issue numbers
=> Add extraTokenParams to ROPC Flow

docs/oidc-client-ts.api.md, src/OidcClient.ts, src/OidcClientSettings.ts, src/ResponseValidator.test.ts, src/ResponseValidator.ts, src/SigninRequest.ts, src/TokenClient.ts
https://github.com/authts/oidc-client-ts/issues/895
=> feature to toggle off pkce

src/ResponseValidator.ts
Closes/fixes #772
Per [response spec](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse), auth_time is conditional dependent on max_age being provided in the request. To fully implement the spec regarding auth_time we would also need access to the request max_age being provided to understand if auth_time is required.
Also renamed variables to assist with logic evaluation. It's likely parameters were being misused based on error messaging, although still valid.
=> Allow auth_time to be undefined on token refresh

src/utils/UrlUtils.ts
This allows using the `OidcClient` class in environments where `window` is undefined.
=> Allow using `OidcClient` without `window` object

src/navigators/IFrameWindow.test.ts, src/navigators/IFrameWindow.ts
Closes #827
Remove obsolete sandbox attribute due to it not being used by Auth0.
=> fix(IFrameWindow): Remove sandbox attribute due to it beeing obsolete

docs/oidc-client-ts.api.md, samples/Parcel/src/oidc-client/sample.js, src/OidcClient.test.ts, src/OidcClient.ts, src/SignoutRequest.ts
Closes/fixes --
- Pass callback URLs to login/logout requests to prevent fatal errors
- Add `client_id` to logout request to prevent fatal errors (tested against Keycloak - either "`id_token_hint`" (already available) or "`client_id`" (missing till now) are required when using `post_logout_redirect_uri`)
=> Fix samples

samples/Parcel/src/oidc-client/sample.js
If I understand right, here is no reason to specify state, since it will be automatically generated and specified value will be overwritten, it is really misleading.
=> fix: remove state attribute from sample requests

docs/oidc-client-ts.api.md, src/OidcClient.test.ts, src/OidcClient.ts, src/RefreshState.ts, src/TokenClient.ts, src/UserManager.test.ts, src/UserManager.ts
Closes/fixes #920 and probably #655
=> Add resource param to signinSilent request

docs/oidc-client-ts.api.md, src/RefreshState.ts, src/index.ts
=> Make 'RefreshState' public

src/navigators/PopupWindow.test.ts, src/navigators/PopupWindow.ts
Added unit tests to provide better code coverage
=> [UnitTests] Popup window not close after some time

src/UserManager.ts
=> Added scriptOrigin parameter for signoutSIlent to work from another origin

.gitignore, dist/esm/package.json, scripts/build.js
This pull request addresses a warning emitted by Webpack that occurs when building the project. The warning indicates the absence of a version specification in the `package.json` of the `dist/esm` directory. To rectify this, I have implemented a solution to automatically copy the version from the main `package.json` to the `dist/esm/package.json` upon each successful build. This resolves the warning and ensures the version information is consistently propagated to the built package.
- Implemented an automatic version copying script from `package.json` to `dist/esm/package.json` after every build.
- Modified the existing build script to incorporate the new version copying functionality.
- Removed unnecessary static package.json
1. Run the build process using the provided build script.
2. …
=> build(esm): dynamically generate package.json for ESM build

src/ResponseValidator.test.ts, src/ResponseValidator.ts
django-oauth-toolkit does not support openid for the resource owner credentials flow. The response will still have openid in the scopes property, but there is not id_token This leads to an exception.
This change makes the client a little more tolerant of auth servers by not trying to parse the id_token in this scenario.
fixes  #1206
- [N/A] This PR makes changes to the public API 
- [*] I have included links for closing relevant issue numbers
=> fix: Exception when id_token not set.

src/ClaimsService.ts
This solution is created based on a bug in merging two claim services.
In more details, the first implementation, whenever a user have a user attribute in the first claim and the second claim, if this attribute has a value of 0, it will be omitted: "!previousValue" line 73 in src/ClaimService.ts, however the expected output should contain that 0. In the solution provided, this previous value is being checked if it is undefined.
- [ No need to update the api report] This PR makes changes to the public API 
- [ No issue number to be included] I have included links for closing relevant issue numbers
=> Fixing a bug in merging token id and user info data. 0 is being omitted.

docs/migration.md, docs/oidc-client-ts.api.md, src/ClaimsService.test.ts, src/ClaimsService.ts, src/OidcClientSettings.ts
Closes/fixes #1232
This merge requests enables a fix for #846 and #852. This MR introduces the new merge behavior and moves all the claims related logic inside a dedicated service.
This code is based on the pre-work done by @marcoreni in #881!
=> improve merge claims behavior

docs/oidc-client-ts.api.md, package-lock.json, package.json, src/OidcClient.test.ts, src/OidcClient.ts, src/SigninRequest.test.ts, src/SigninRequest.ts, src/SigninState.test.ts, src/SigninState.ts, src/State.test.ts, src/State.ts, src/index.ts, src/utils/CryptoUtils.ts, test/setup.ts
=> use web crypto instead of cryptojs

docs/oidc-client-ts.api.md, src/OidcClient.ts, src/UserManager.ts
Closes/fixes [#1257](https://github.com/authts/oidc-client-ts/issues/1257)
=> Added extraTokenParams to UserManager.signinSilent

docs/oidc-client-ts.api.md, src/OidcClient.test.ts, src/OidcClient.ts, src/RefreshState.ts, src/TokenClient.ts, src/UserManager.test.ts, src/UserManager.ts
Closes/fixes #1175
Removes the `resource` prop from the state and adds it into the args to pass down to the `exchangeRefreshToken` function. Treat `resource`, `extraTokenParams` and `redirect_uri` and any future prop the same way.
=> allow to optionally pass redirect_uri into exchangeRefreshToken

src/utils/CryptoUtils.ts
=> explicitly throw an error when crypto.subtle is undefined

docs/oidc-client-ts.api.md, src/SessionMonitor.ts, src/SilentRenewService.ts, src/UserManager.test.ts, src/UserManager.ts, src/UserManagerEvents.test.ts, src/UserManagerEvents.ts, src/navigators/IFrameWindow.ts, src/navigators/PopupWindow.ts, src/utils/Event.test.ts, src/utils/Event.ts, src/utils/Timer.test.ts, src/utils/Timer.ts
=> handle promise in Events.raise

.gitignore, src/UserManager.test.ts, src/UserManager.ts
This PR prevents race conditions with event handlers which react to this unload event and expect the user to be signed out already.
Fixes #1341
=> Fix too early `UserManager.events().unload()` event before user is actually signed out

.gitignore, docs/migration.md, src/UserManager.test.ts, src/UserManager.ts
Closes/fixes #1379
Lessons learnt:
- It is not 100% reliable that the logout is called (session must be seen by the IDP as valid)
- The remove of the user must happen due to stability reasons before the sign-out request
- The <3.0 behavior is very simple and works 100% reliable
Future:
- To be clarified if we can suppress reliable always the unload user event in that situation
- with callback: it might be not needed at all, as the client reloads multiple times anyway
- without callback: for some IDP we land on the IDP signout and not our application
=> Fix 1379 revert 1341

docs/oidc-client-ts.api.md, src/JsonService.test.ts, src/JsonService.ts, src/OidcClient.test.ts, src/OidcClient.ts, src/ResponseValidator.ts, src/TokenClient.test.ts, src/TokenClient.ts, src/UserManager.ts
This adds the extraHeaders plumbing that will be required to implement DPoP, re: #1361 as per [this request](https://github.com/authts/oidc-client-ts/pull/1361#issuecomment-2011905006).
Decided not to both adding extraHeaders to methods relating to the Resource Owner Password Credentials grant as it Is actively discouraged in the latest version of the [OAuth2 BCP](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#name-resource-owner-password-cre).
=> Add extra headers

docs/oidc-client-ts.api.md, src/UserManager.ts
I accidentally added the extraHeaders parameter separately to what I'd already added to the USeRefreshTokenArgs. This removes the double up.
=> Remove unneccesary extraHeaders parameter from _useRefreshToken

src/UserManager.ts
signinCallback documentation seemed to have been copy/pasted from signoutCallback leading to a confusing doc.
=> fix small typo in signinCallback doc in UserManager.ts

docs/oidc-client-ts.api.md, src/DPoPStore.ts, src/IndexedDbDPoPStore.test.ts, src/IndexedDbDPoPStore.ts, src/JsonService.test.ts, src/JsonService.ts, src/OidcClient.test.ts, src/OidcClient.ts, src/UserManager.test.ts, src/UserManager.ts, src/errors/ErrorDPoPNonce.ts, src/index.ts, src/utils/CryptoUtils.test.ts, src/utils/CryptoUtils.ts
This is a first cut aimed at adding `DPoP` nonce support. I initially removed this feature in the original [PR](https://github.com/authts/oidc-client-ts/pull/1461) and this is a follow up.
This is very experimental and open to change. @pamapa I would really appreciate your thoughts as to how this could be done more cleanly 🙏🏼
The main functionality is supporting [Authorization Server Provided Nonces](https://datatracker.ietf.org/doc/html/rfc9449#name-authorization-server-provid).
According to the spec, if/when an AS requires the use of a nonce and a token request is made without a nonce claim within the DPoP proof JWT, the AS responds with a specific 400 bad request that includes a response header `dpop-nonce` which contains the nonce value to be used. The client is then expected to …
=> Add dpop nonce support

docs/index.md, docs/protocols/demonstrating-proof-of-possession.md
This adds some basic documentation for Demonstrating Proof of Possession.
=> Add DPoP docs first cut

src/ResponseValidator.ts, src/utils/Event.ts
When using target `ES2022` those error will arise. We are currently using `ES2019`.
=> Fix future compiler error

docs/index.md
It seems like there is no `Oidc.Log`, I had to use just `Log`.
However I'm still confused about the correct usage. After this:
```
import { Log } from 'oidc-client-ts';
Log.setLogger(console);
Log.setLevel(Log.DEBUG)
```
I see logs things like `[UserManager] getUser: user loaded`, but still not [this log at token renewal](https://github.com/authts/oidc-client-ts/blob/8181652f609242dd14ee1ae4f6b82a9a5116f966/src/SilentRenewService.ts#L51).
=> updated docs about logger

docs/oidc-client-ts.api.md, src/UserManager.ts, src/navigators/PopupNavigator.ts, src/navigators/PopupWindow.test.ts, src/navigators/PopupWindow.ts
Closes: #1625
- Adds `popupSignal` property to `signinPopup` and `signoutPop` methods to cancel windows similar to [fetch signal](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#canceling_a_request)
=> Popup Abort Signals

docs/oidc-client-ts.api.md, src/OidcClient.test.ts, src/OidcClient.ts
Use case:
We have a custom extension to OAuth/OIDC where the `code` is an OTP that the user is sent when the OAuth handshake starts. This code is used instead of the typical randomly generated code in exchange for an access token.
If this code is incorrect, the user cannot retry as the state (including PKCE challenge) gets removed from the store as soon as the code is used. With this change, we can pass `removeState = true` which means even if the validation fails, it can be reattempted with a different code.
Without this change, we have to mimic the behaviour of `processSigninResponse` by:
- Calling `readSigninResponseState` directly with `removeState = false`
- Editing the prototype of `OidcClient` so that `_validator.validateSigninResponse()` can be called by the application.
```ts …
```
=> Add `removeState` as an option to `processSigninResponse`

src/JsonService.test.ts, src/JsonService.ts
=> cannot set Authorization via extraHeaders

src/TokenClient.ts
Closes/fixes #1068 and #1438
This pull request includes changes to the TokenClient class in the src/TokenClient.ts file to improve the handling of the client_secret parameter. The changes ensure that the client_secret is explicitly checked for undefined or null values, rather than using a falsy check. This modification allows empty strings as valid client_secret values when using client_secret_basic authentication method, which was previously rejected by the falsy check.
=> allow empty string for client_secret in TokenClient

docs/oidc-client-ts.api.md, src/OidcClient.test.ts, src/OidcClient.ts, src/SignoutRequest.test.ts, src/SignoutRequest.ts, src/SignoutResponse.test.ts, src/SignoutResponse.ts, src/UserManager.test.ts, src/UserManager.ts
Extends the fix added for #293 in PR https://github.com/authts/oidc-client-ts/pull/1212 to also cover sign out.
For background I believe the same principles regarding `state` for sign in within the linked issue also apply in the sign out case as well. I am working with a multi-tenant system that has a proxy to resolve the actual hostname for the redirect_uri, which also needs to send a signed-out user back to the application start page on the right hostname.
Without this fix, I would need to configure every potential hostname as a valid redirect URI in the IDP client config (whilst I think Keycloak can allow wildcards, it's not recommended and others such as Entra ID do not).
This change replicates the concatenated internal opaque state value with a custom `url_state` value and delimiter …
=> Add url_state to SignoutRequest

src/MetadataService.test.ts, src/MetadataService.ts
Closes/fixes https://github.com/authts/oidc-client-ts/issues/1803
-----
See linked issue for details.
It appears as if the `metadataSeed` merging was reversed, meaning it had no effect once merged with the remote metadata.
This PR ensures that `metadataSeed` overrides the remote metadata, in case the same key is defined in both.
=> Ensure `metadataSeed` has priority over remote metadata

docs/oidc-client-ts.api.md, src/UserManager.test.ts, src/UserManager.ts
Relates to #712 and provides a solution that is backwards-compatible and will fix an issue for some users.
Adding a new parameter `raiseEvent = false` to the `UserManager.getUser()` method to allow execute the `addUserLoaded()` event handlers after raising the `userLoaded` event.
**Background**: The `userLoaded` event does currently not get raised whenever the `user` value is being read from the local storage, which happens whenever no user data has to be fetched from the authority but from the store. In #712 developers complained about this behavior since some business-logic depends on the `getUser()`/`userLoaded` method/event for .e.g. loading additional user-related data from third-party sources like APIs. In the case that a user is already authenticated and e.g. reloads the page, the …
=> Adds raiseEvent parameter to getUser() method

src/ResponseValidator.test.ts, src/ResponseValidator.ts
If we have a Resource Owner Password Flow and token endpoint does not return `token_id` in the response while returning scope: `openid` it will fail the sub claim check.
```
if (validateSub && claims.sub !== response.profile.sub) {
logger.throw(new Error("subject from UserInfo response does not match subject in ID Token"));
}
```
After some investigation, i noticed that if we don't have token_id ``_validateIdTokenAttributes`` will be skipped which means that ``response.profile`` will always be an empty object and always fail the check ``(validateSub && claims.sub !== response.profile.sub)``
=> fix: Resource Owner Password Credentials flow with oidc scope and no id_token returned will fail sub claim check
